### ISSUE TITLE
container fluid

### ISSUE THREAD

**Issue by ninja-yan** [ckrack/fbootstrapp#18]
Hi everyone!
Having problem using container fluid in fbootstrap.no scroll down..i can see the contents below. how to fix it? thanks

**Comment by ninja-yan** [comment]
Solved!

**Comment by ApolloCTP** [comment]
Hi, I am having the same issue. Could you please post your solution? Thanks.

**Comment by ninja-yan** [comment]
Oh I already forgot but if I remember it correctly I used overflow: hidden / show 
Sorry I no longer have the code

**Comment by ninja-yan** [comment]
Oh I remember it already.

css code

body {
  overflow: visible;
}
