### ISSUE TITLE
Popover arrow has no border

### ISSUE THREAD

**Issue by ghost** [ckrack/fbootstrapp#2]
Mac OS X 10.7.2 | Chrome 16.0.912.75

Popover arrow is completely white, instead of continuing the box border.

Pic:
https://twitter.com/#!/leonardoperna/status/156483114976280577/photo/1/large

**Comment by ckrack** [comment]
Are you using the latest version?
This should be fixed with this commit:
https://github.com/ckrack/fbootstrapp/commit/367956a94605358dd7fc1174de32d0a6310a93de

**Comment by ckrack** [comment]
Actually i didn't push that to the gh-pages branch.
Thanks for the notice.
