### ISSUE TITLE
Why my mouse scroll (down/up) does work ?

### ISSUE THREAD

**Issue by navotera** [ckrack/fbootstrapp#28]
Im using this library, i think the problem is when i insert / link bootstrap.css (fbootstrap) into my code then my mouse stacked, it cannot scroll down/top

is there any js/css should i insert others than main bootstrap.css ??

**Comment by hvsombrilla** [comment]
You need to remove `overflow:hidden;`  from line 100 of bootstrap.min.css or 483 in bootstrap.css
