### ISSUE TITLE
Padding in select elements in Firefox 9

### ISSUE THREAD

**Issue by jwf-zz** [ckrack/fbootstrapp#4]
In Firefox 9.0.1 (maybe others, didn't test), the select boxes seem to have some padding (4px all around), so the text is somewhat obscured. It seems like Firefox is ignoring the "padding: initial;" rule. However, this doesn't cause problems in Bootstrap because the height and line-height are 27px (so it just looks kind of funny, but still readable), but you've made them 21px, so in Firefox the text gets chopped.

**Comment by ckrack** [comment]
Thanks for the insightful report.

I have added a padding: 2px; above the padding: initial;
That way browsers that understand the initial value will override the 2px and firefox will keep that.
