### ISSUE TITLE
overflow-y:scroll

### ISSUE THREAD

**Issue by ptarjan** [ckrack/fbootstrapp#6]
Why do you have a forced scrollbar on the <html> element? For pages that fit vertically, there is no need to have an ugly scrollbar.

You can try removing my CSS stylesheet from here to see what I mean: http://apps.facebook.com/imdb_top_two_fifty/

**Comment by ckrack** [comment]
Thanks for the catch, that was left in there from Bootstrap.
Of course, since FB Apps are based on iframes this is usually not intended
behaviour.

I'm pushing a fix now.
