### ISSUE TITLE
Modals in iframes

### ISSUE THREAD

**Issue by codecowboy** [ckrack/fbootstrapp#8]
In an iframe application, is there a way to have the modal appear above the canvas? Otherwise the modal only affects the iframe and the modal is cropped. My use case is a 520px page tab application

**Comment by ckrack** [comment]
Nope, iframe content is limited to the iframe itself.
This is not a fbootstrapp issue, as it is behaviour that is implemented in the way iframes are handled by browsers.

Actually, if that was possible, it could be used for phishing and would be very confusing for users.
Iframes can contain content from origins, that are not controlled by the site they are refered from (just as it is the case with facebook apps).

**Comment by salt-istanbul** [comment]
These callback functions works well for modal view on iframe application with setAutoGrow.

$("#modal-upload").bind('hidden', function () {
     FB.Canvas.setAutoGrow();
});
$("#modal-upload").bind('show', function () {
         FB.Canvas.setAutoGrow(false);
     FB.Canvas.setSize({ width: 810, height: 800 });
});
